SUCCESS_CODE = 200
API_FAILED = "Api failed, Something went wrong."
CSGO_EMPIRE_BASE_URL = "https://csgoempire.com/api/v2"
MARKET_CSGO_BASE_URL = "https://market.csgo.com/api/v2" 
WAXPEER_BASE_URL = "https://api.waxpeer.com/v1"
ITEM_NOT_FOUND = "Item not found"
SUCCESS = "true"
FAILURE = "false"
PRICEEMPIRE_URL = "https://api.pricempire.com/v3"
